serve:
  port: 3100

# 缓存配置
cache:
  redis: # 有值时，使用 redis 做缓存服务器
    host: 'localhost'
    port: 6379

# 限流
httpLimiter:
  tokenKey: 'nestHttpLimiter' #剩余tokenKey
  timestampKey: 'nestHttpLimiterStamp' #刷新时间Key
  capacity: 100 #桶容量
  rate: 1 #每秒生成token数量即token生成速度

  # Swagger 配置
swagger:
  title: 项目接口文档
  description: '[Base URL: localhost:3100]'
  path: v1/swagger

  # 数据库配置
datasource:
  driverName: mysql
  host: localhost
  port: 3306
  database: nestjsMysqlApi
  username: root
  password: 123456
  charset: utf8mb4
  loc: Asia/Shanghai
  logging: true